### ISSUE TITLE
Unexpected syllables for several examples

### ISSUE THREAD

**Issue by factormystic** [nlp-compromise/nlp-syllables#2]
text: `he's got a document`
expected: 6 total
actual: 

```
[ [ [ 'he\'he\'s' ],
[],
[ 'got' ],
[ 'a' ],
[ 'doc', 'um', 'en', 't' ] ] ]
```

Looks like `he's` and `document` are coming out wrong

**Comment by factormystic** [comment]
another one: `something` => `[ 'som', 'et', 'hin', 'g' ]`, would expect `[ 'some', 'thing' ]`

**Comment by factormystic** [comment]
decided to work on these myself... should have a PR in a few days with some improvements...

**Comment by spencermountain** [comment]
thaaaaanks!
